import fs from 'fs';
import os from 'os';
import path from 'path';
import {
  detectSourceFromCkbToml,
  expectedGenesisHash,
  markForkFirstRunComplete,
  parseGenesisHashFromInitOutput,
  parseGenesisHashFromListHashes,
  patchDevSpecForFork,
  readForkState,
  writeForkState,
  ForkState,
  copySourceData,
  isolateForkCkbConfig,
  migrationNeededFromExitCode,
  forkDevnet,
} from '../src/devnet/fork';
import { identifyPublicChainByGenesisHash, MAINNET_GENESIS_HASH, TESTNET_GENESIS_HASH } from '../src/scripts/const';

describe('detectSourceFromCkbToml', () => {
  it('detects mainnet from a bundled spec', () => {
    const content = `[chain]\nspec = { bundled = "specs/mainnet.toml" }\n`;
    expect(detectSourceFromCkbToml(content)).toBe('mainnet');
  });

  it('detects testnet from a bundled spec', () => {
    const content = `[chain]\nspec = { bundled = "specs/testnet.toml" }\n`;
    expect(detectSourceFromCkbToml(content)).toBe('testnet');
  });

  it('returns null for a file-based (dev/custom) spec', () => {
    const content = `[chain]\nspec = { file = "specs/dev.toml" }\n`;
    expect(detectSourceFromCkbToml(content)).toBeNull();
  });

  it('returns null for invalid toml', () => {
    expect(detectSourceFromCkbToml('not = [valid')).toBeNull();
  });

  it('returns null when chain spec is missing', () => {
    expect(detectSourceFromCkbToml('[logger]\nfilter = "info"\n')).toBeNull();
  });
});

describe('parseGenesisHashFromInitOutput', () => {
  it('parses the genesis hash from ckb init output', () => {
    const output = [
      'WARN: Mining feature is disabled because of the lack of the block assembler config options.',
      'Initialized CKB directory in /tmp/foo',
      'copy /tmp/testnet.toml to specs/dev.toml',
      'Create ckb.toml',
      'Genesis Hash: 0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606',
    ].join('\n');
    expect(parseGenesisHashFromInitOutput(output)).toBe(TESTNET_GENESIS_HASH);
  });

  it('returns null when the output has no genesis hash', () => {
    expect(parseGenesisHashFromInitOutput('Initialized CKB directory')).toBeNull();
  });
});

describe('parseGenesisHashFromListHashes', () => {
  it('parses the genesis hash from ckb list-hashes output', () => {
    const output = [
      '# Generated by: ckb list-hashes -C /tmp/ckb-testnet',
      '[bundled-testnet]',
      'spec_hash = "0xfdf112fc3d75f1aa1b66fd756a18171a9fd4aeec0f67ea8e1a2c99d1a28dbe21"',
      'genesis = "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606"',
      'cellbase = "0xcf17b48021d1644f6740288eb74e823ea53d598c25b3876a9b957ab5ee3d00f2"',
    ].join('\n');
    expect(parseGenesisHashFromListHashes(output)).toBe(TESTNET_GENESIS_HASH);
  });

  it('accepts uppercase hex and normalizes to lowercase', () => {
    const output = '[offckb]\ngenesis = "0x10639E0895502B5688A6BE8CF69460D76541BFA4821629D86D62BA0AAE3F9606"\n';
    expect(parseGenesisHashFromListHashes(output)).toBe(TESTNET_GENESIS_HASH);
  });

  it('returns null when there is no genesis field', () => {
    expect(parseGenesisHashFromListHashes('[offckb]\nspec_hash = "0x00"\n')).toBeNull();
  });
});

describe('expectedGenesisHash / identifyPublicChainByGenesisHash', () => {
  it('maps both public chains', () => {
    expect(expectedGenesisHash('mainnet')).toBe(MAINNET_GENESIS_HASH);
    expect(expectedGenesisHash('testnet')).toBe(TESTNET_GENESIS_HASH);
    expect(identifyPublicChainByGenesisHash(MAINNET_GENESIS_HASH)).toBe('mainnet');
    expect(identifyPublicChainByGenesisHash(TESTNET_GENESIS_HASH)).toBe('testnet');
    expect(identifyPublicChainByGenesisHash('0x' + '00'.repeat(32))).toBeNull();
    expect(identifyPublicChainByGenesisHash(undefined)).toBeNull();
  });
});

describe('patchDevSpecForFork', () => {
  it('applies the common dev patch on a spec without a params section (testnet)', () => {
    const spec = {
      name: 'ckb_testnet',
      genesis: { version: 0 },
      pow: { func: 'EaglesongBlake2b' },
    };
    const patched = patchDevSpecForFork(spec, 'testnet') as Record<string, any>;

    expect(patched.pow.func).toBe('Dummy');
    expect(patched.params.cellbase_maturity).toBe(0);
    expect(patched.params.permanent_difficulty_in_dummy).toBe(true);
    expect('genesis_epoch_length' in patched.params).toBe(false);
    // untouched sections stay as-is
    expect(patched.name).toBe('ckb_testnet');
    expect(patched.genesis).toEqual({ version: 0 });
  });

  it('removes a wrong genesis_epoch_length on testnet (ckb#5205 regression)', () => {
    // ckb < v0.207.0 wrote genesis_epoch_length = 1743 into imported testnet
    // specs, which changes the genesis hash and bricks the fork.
    const spec = {
      pow: { func: 'EaglesongBlake2b' },
      params: { genesis_epoch_length: 1743 },
    };
    const patched = patchDevSpecForFork(spec, 'testnet') as Record<string, any>;
    expect('genesis_epoch_length' in patched.params).toBe(false);
  });

  it('forces genesis_epoch_length = 1743 on mainnet', () => {
    const spec = {
      pow: { func: 'Eaglesong' },
      params: { genesis_epoch_length: 1743, initial_primary_epoch_reward: 191780821917808 },
    };
    const patched = patchDevSpecForFork(spec, 'mainnet') as Record<string, any>;
    expect(patched.params.genesis_epoch_length).toBe(1743);
    expect(patched.params.cellbase_maturity).toBe(0);
    expect(patched.params.permanent_difficulty_in_dummy).toBe(true);
    // economic params of the source chain are preserved
    expect(patched.params.initial_primary_epoch_reward).toBe(191780821917808);
  });

  it('restores genesis_epoch_length on mainnet even if missing', () => {
    const patched = patchDevSpecForFork({ pow: {} }, 'mainnet') as Record<string, any>;
    expect(patched.params.genesis_epoch_length).toBe(1743);
  });

  it('keeps a custom spec genesis_epoch_length untouched', () => {
    const spec = { pow: { func: 'Eaglesong' }, params: { genesis_epoch_length: 500 } };
    const patched = patchDevSpecForFork(spec, 'custom') as Record<string, any>;
    expect(patched.params.genesis_epoch_length).toBe(500);
    expect(patched.pow.func).toBe('Dummy');
  });

  it('does not mutate the input spec object', () => {
    const spec = { pow: { func: 'Eaglesong' }, params: { genesis_epoch_length: 1743 } };
    patchDevSpecForFork(spec, 'testnet');
    expect(spec.pow.func).toBe('Eaglesong');
    expect(spec.params.genesis_epoch_length).toBe(1743);
  });
});

describe('fork data isolation and migration preflight', () => {
  let root: string;
  beforeEach(() => {
    root = fs.mkdtempSync(path.join(os.tmpdir(), 'offckb-fork-copy-test-'));
  });
  afterEach(() => fs.rmSync(root, { recursive: true, force: true }));

  it('copies chain state without persisted peers or transient data', () => {
    const source = path.join(root, 'source');
    const target = path.join(root, 'target');
    for (const entry of ['db', 'indexer', 'network/peer_store', 'logs', 'tmp']) {
      fs.mkdirSync(path.join(source, 'data', entry), { recursive: true });
      fs.writeFileSync(path.join(source, 'data', entry, 'fixture'), entry);
    }

    copySourceData(source, target);

    expect(fs.existsSync(path.join(target, 'data', 'db', 'fixture'))).toBe(true);
    expect(fs.existsSync(path.join(target, 'data', 'indexer', 'fixture'))).toBe(true);
    expect(fs.existsSync(path.join(target, 'data', 'network'))).toBe(false);
    expect(fs.existsSync(path.join(target, 'data', 'logs'))).toBe(false);
    expect(fs.existsSync(path.join(target, 'data', 'tmp'))).toBe(false);
  });

  it('forces forked nodes into an outbound-isolated network config', () => {
    const config = isolateForkCkbConfig({
      network: { bootnodes: ['mainnet-peer'], max_outbound_peers: 8, discovery_local_address: true },
      logger: { filter: 'warn,ckb-script=debug' },
    }) as Record<string, any>;

    expect(config.network).toEqual(
      expect.objectContaining({
        bootnodes: [],
        max_outbound_peers: 0,
        whitelist_only: true,
        discovery_local_address: false,
      }),
    );
    expect(config.logger.filter).toBe('warn');
  });

  it('understands ckb migrate --check exit codes', () => {
    expect(migrationNeededFromExitCode(0)).toBe(true);
    expect(migrationNeededFromExitCode(64)).toBe(false);
    expect(() => migrationNeededFromExitCode(1)).toThrow('migrate --check failed');
    expect(() => migrationNeededFromExitCode(null)).toThrow('migrate --check failed');
  });
});

describe('fork input mode', () => {
  it('requires an explicit source directory for a database fork', async () => {
    await expect(forkDevnet({})).rejects.toThrow('Database fork requires a source CKB directory');
  });
});

describe('fork state file', () => {
  let dir: string;
  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), 'offckb-fork-test-'));
  });
  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  const state: ForkState = {
    source: 'testnet',
    sourceDir: '/data/ckb-testnet',
    ckbVersion: '0.207.0',
    genesisHash: TESTNET_GENESIS_HASH,
    forkedAt: '2026-07-17T00:00:00.000Z',
    firstRunPending: true,
  };

  it('returns null when no state file exists', () => {
    expect(readForkState(dir)).toBeNull();
  });

  it('round-trips the state', () => {
    writeForkState(dir, state);
    expect(readForkState(dir)).toEqual(state);
  });

  it('returns null for a corrupt state file', () => {
    fs.writeFileSync(path.join(dir, 'fork.json'), '{oops');
    expect(readForkState(dir)).toBeNull();
  });

  it('clears firstRunPending and records the fork boundary while preserving the other fields', () => {
    writeForkState(dir, state);
    markForkFirstRunComplete(dir, '123');
    const updated = readForkState(dir);
    expect(updated).toEqual({ ...state, firstRunPending: false, forkBlockNumber: '123' });
  });

  it('markForkFirstRunComplete is a no-op without a state file', () => {
    expect(() => markForkFirstRunComplete(dir)).not.toThrow();
    expect(readForkState(dir)).toBeNull();
  });
});
