import { resolveDevnetSystemScripts, toCCCKnownScripts, buildDevnetCCCClient } from '../src/scripts/private';
import { MAINNET_SYSTEM_SCRIPTS, TESTNET_SYSTEM_SCRIPTS } from '../src/scripts/public';
import { MAINNET_GENESIS_HASH, TESTNET_GENESIS_HASH } from '../src/scripts/const';

// Real `ckb list-hashes` output (trimmed) of a testnet fork: only the four
// genesis system cells and two dep groups, genesis = testnet genesis hash.
const TESTNET_FORK_LIST_HASHES = `# Generated by: ckb list-hashes
[ckb_testnet]
spec_hash = "0x1c7f66f909b7ab4349fe71d191cacb8d1d5f3b96a0368cc6389deeb7eef2601e"
genesis = "${TESTNET_GENESIS_HASH}"
cellbase = "0x8f8c79eb6671709633fe6a46de93c0fedc9c1b8a6527a18d3983879542635c9f"

[[ckb_testnet.system_cells]]
path = "Bundled(specs/cells/secp256k1_blake160_sighash_all)"
tx_hash = "0x8f8c79eb6671709633fe6a46de93c0fedc9c1b8a6527a18d3983879542635c9f"
index = 1
data_hash = "0x709f3fda12f561cfacf92273c57a98fede188a3f1a59b1f888d113f9cce08649"
type_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"

[[ckb_testnet.system_cells]]
path = "Bundled(specs/cells/dao)"
tx_hash = "0x8f8c79eb6671709633fe6a46de93c0fedc9c1b8a6527a18d3983879542635c9f"
index = 2
data_hash = "0x32064a14ce10d95d4b7343054cc19d73b25b16ae61a6c681011ca781a60c7923"
type_hash = "0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e"

[[ckb_testnet.system_cells]]
path = "Bundled(specs/cells/secp256k1_data)"
tx_hash = "0x8f8c79eb6671709633fe6a46de93c0fedc9c1b8a6527a18d3983879542635c9f"
index = 3
data_hash = "0x9799bee251b975b82c45a02154ce28cec89c5853ecc14d12b7b8cccfc19e0af4"

[[ckb_testnet.system_cells]]
path = "Bundled(specs/cells/secp256k1_blake160_multisig_all)"
tx_hash = "0x8f8c79eb6671709633fe6a46de93c0fedc9c1b8a6527a18d3983879542635c9f"
index = 4
data_hash = "0x43400de165f0821abf63dcac299bbdf7fd73898675ee4ddb099b0a0d8db63bfb"
type_hash = "0x5c5069eb0857efc65e1bca0c07df34c31663b3622fd3876c876320fc9634e2a8"

[[ckb_testnet.dep_groups]]
included_cells = ["Bundled(specs/cells/secp256k1_data)", "Bundled(specs/cells/secp256k1_blake160_sighash_all)"]
tx_hash = "0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37"
index = 0

[[ckb_testnet.dep_groups]]
included_cells = ["Bundled(specs/cells/secp256k1_data)", "Bundled(specs/cells/secp256k1_blake160_multisig_all)"]
tx_hash = "0x4ace50a3d0e04d7cc8a3f4e24f5ab3c7b29b5c40e2be0c4ae3ddce2f96a95a37"
index = 0
`;

const MAINNET_FORK_LIST_HASHES = TESTNET_FORK_LIST_HASHES.replaceAll('ckb_testnet', 'ckb').replace(
  `genesis = "${TESTNET_GENESIS_HASH}"`,
  `genesis = "${MAINNET_GENESIS_HASH}"`,
);

// A pure offckb devnet: genesis does not match any public chain.
const PURE_DEVNET_LIST_HASHES = TESTNET_FORK_LIST_HASHES.replace(
  `genesis = "${TESTNET_GENESIS_HASH}"`,
  `genesis = "0x${'11'.repeat(32)}"`,
);

const mockGetDevnetListHashes = jest.fn();
jest.mock('../src/util/list-hashes', () => ({
  getDevnetListHashes: () => mockGetDevnetListHashes(),
}));

jest.mock('../src/cfg/setting', () => ({
  readSettings: () => ({
    bins: { defaultCKBVersion: '0.207.0' },
    devnet: { configPath: '/tmp/offckb-devnet-config' },
  }),
}));

jest.mock('../src/util/logger', () => ({
  logger: {
    success: jest.fn(),
    info: jest.fn(),
    warn: jest.fn(),
    error: jest.fn(),
    debug: jest.fn(),
    setJsonMode: jest.fn(),
  },
}));

describe('resolveDevnetSystemScripts', () => {
  beforeEach(() => {
    mockGetDevnetListHashes.mockReset();
  });

  it('returns null when list-hashes is unavailable', () => {
    mockGetDevnetListHashes.mockReturnValue(null);
    expect(resolveDevnetSystemScripts()).toBeNull();
  });

  it('resolves genesis scripts from list-hashes on a pure devnet, without supplementation', () => {
    mockGetDevnetListHashes.mockReturnValue(PURE_DEVNET_LIST_HASHES);
    const resolved = resolveDevnetSystemScripts();

    expect(resolved).not.toBeNull();
    expect(resolved!.forkedFrom).toBeNull();
    const scripts = resolved!.scripts;
    expect(scripts.secp256k1_blake160_sighash_all!.script.codeHash).toBe(
      '0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8',
    );
    // not in genesis of a plain 4-cell spec, and no static record applies
    expect(scripts.omnilock).toBeUndefined();
    expect(scripts.xudt).toBeUndefined();
    expect(scripts.type_id).toBeDefined();
  });

  it('identifies a testnet fork by genesis hash and supplements post-genesis scripts', () => {
    mockGetDevnetListHashes.mockReturnValue(TESTNET_FORK_LIST_HASHES);
    const resolved = resolveDevnetSystemScripts();

    expect(resolved!.forkedFrom).toBe('testnet');
    expect(resolved!.genesisHash).toBe(TESTNET_GENESIS_HASH);
    const scripts = resolved!.scripts;

    // genesis scripts still come from list-hashes (the chain's own spec):
    // secp256k1 is referenced via its dep group, dao via its own cell
    expect(scripts.secp256k1_blake160_sighash_all!.script.cellDeps[0].cellDep.outPoint.txHash).toBe(
      '0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37',
    );
    expect(scripts.secp256k1_blake160_sighash_all!.script.cellDeps[0].cellDep.depType).toBe('depGroup');
    expect(scripts.dao!.script.codeHash).toBe('0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e');

    // post-genesis scripts are filled from the testnet static record
    expect(scripts.omnilock!.script.codeHash).toBe(TESTNET_SYSTEM_SCRIPTS.omnilock!.script.codeHash);
    expect(scripts.xudt!.script.codeHash).toBe(TESTNET_SYSTEM_SCRIPTS.xudt!.script.codeHash);
    expect(scripts.sudt!.script.codeHash).toBe(TESTNET_SYSTEM_SCRIPTS.sudt!.script.codeHash);
    expect(scripts.anyone_can_pay!.script.codeHash).toBe(TESTNET_SYSTEM_SCRIPTS.anyone_can_pay!.script.codeHash);

    // ccc known scripts must be buildable on a fork (used by transfer/deploy)
    expect(() => toCCCKnownScripts(scripts)).not.toThrow();
  });

  it('identifies a mainnet fork by genesis hash and uses the mainnet record', () => {
    mockGetDevnetListHashes.mockReturnValue(MAINNET_FORK_LIST_HASHES);
    const resolved = resolveDevnetSystemScripts();

    expect(resolved!.forkedFrom).toBe('mainnet');
    const scripts = resolved!.scripts;
    expect(scripts.omnilock!.script.codeHash).toBe(MAINNET_SYSTEM_SCRIPTS.omnilock!.script.codeHash);
    expect(scripts.sudt!.script.codeHash).toBe(MAINNET_SYSTEM_SCRIPTS.sudt!.script.codeHash);
    expect(scripts.xudt!.script.codeHash).toBe(MAINNET_SYSTEM_SCRIPTS.xudt!.script.codeHash);
  });

  it('does not mutate or share objects with the static records', () => {
    mockGetDevnetListHashes.mockReturnValue(TESTNET_FORK_LIST_HASHES);
    const resolved = resolveDevnetSystemScripts();
    const scripts = resolved!.scripts;

    expect(scripts.omnilock).not.toBe(TESTNET_SYSTEM_SCRIPTS.omnilock);
    scripts.omnilock!.script.cellDeps.length = 0;
    expect(TESTNET_SYSTEM_SCRIPTS.omnilock!.script.cellDeps.length).toBeGreaterThan(0);
  });
});

describe('buildDevnetCCCClient', () => {
  beforeEach(() => {
    mockGetDevnetListHashes.mockReset();
  });

  it('uses the ckt prefix on a pure/testnet devnet', () => {
    mockGetDevnetListHashes.mockReturnValue(TESTNET_FORK_LIST_HASHES);
    const client = buildDevnetCCCClient('http://127.0.0.1:8114');
    expect(client.addressPrefix).toBe('ckt');
  });

  it('uses the ckb prefix on a mainnet fork so ckb1 addresses parse', () => {
    mockGetDevnetListHashes.mockReturnValue(MAINNET_FORK_LIST_HASHES);
    const client = buildDevnetCCCClient('http://127.0.0.1:8114');
    expect(client.addressPrefix).toBe('ckb');
  });
});
